language: ruby
bundler_args: --without extras --standalone --binstubs
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby
  - rbx
services:
  - redis-server
script: bin/rake ci --trace
notifications:
  email:
    - moz-platform-dev@seomoz.org
matrix:
  # These fail because of keyword arguments.
  allow_failures:
    - rvm: rbx
    - rvm: jruby
