language: ruby
bundler_args: --without extras --standalone --binstubs
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode
  - rbx
services:
  - redis-server
script: bin/rake ci --trace
notifications:
  email:
    - moz-platform-dev@seomoz.org
matrix:
  allow_failures:
    - rvm: rbx

