language: ruby
bundler_args: --without extras
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
services:
  - redis-server
notifications:
  email:
    - moz-platform-dev@seomoz.org
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

